create Toaster
mambojs/mambo-ui pull request #116
Opened 2024-11-18 15:44 UTC by diegonicita

2024-11-19 02:40 UTC, alejandroscotti requested changes

2024-11-19 02:40 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster-Orange.css
> +  border: 1px solid var(--m-gray-200);
Este estilo y el background **white** los veo sospechosos... por que gris y blanco?
`border: 1px solid var(--m-gray-200);`

2024-11-19 02:40 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster-Orange.css
> +  color: var(--m-white-color);
Por que color blanco?

2024-11-19 02:40 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster.css
> +.m-toaster-self.m-toaster-informative {
Cambiar de **informative** a simplemente **info**

2024-11-19 02:40 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster.css
> +  color: var(--m-black-color);
Por que color negro?

2024-11-19 02:40 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster.js
> +			if (!self.isConnected) {
Por que no hay renglon vacio antes y despues del bloque `if () {}`? el auto formateador deberia haberlo agregado al espacio

2024-11-19 02:40 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster.js
> +				if (m_position.vertical === "center") {
Por que no hay renglon vacio antes y despues del bloque `if () {}`? el auto formateador deberia haberlo agregado al espacio

2024-11-19 02:40 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster.js
> +					anchorOrigin: { horizontal: "left", vertical: "bottom" },
Que la posicion por defecto sea centro/arriba

2024-11-19 02:40 UTC, alejandroscotti commented on src/ui/themes/m-default.css
> +  --m-informative-color: #1C51A4;
**informative** --> **info**

2024-11-19 18:18 UTC, diegonicita commented on src/ui/components/Toaster/Toaster-Orange.css
> +  border: 1px solid var(--m-gray-200);
Ya lo corregi. Faltaba copiar los estilos desde Toaster.css

2024-11-19 18:18 UTC, diegonicita commented on src/ui/components/Toaster/Toaster-Orange.css
> +  color: var(--m-white-color);
Ya lo corregi. Faltaba copiar los estilos desde Toaster.css

2024-11-19 18:18 UTC, diegonicita commented on src/ui/components/Toaster/Toaster.css
> +.m-toaster-self.m-toaster-informative {
cambiado.

2024-11-19 18:19 UTC, diegonicita commented on src/ui/components/Toaster/Toaster.css
> +  color: var(--m-black-color);
agregue variables con colores para hover (info, warning, error, success)

2024-11-19 18:21 UTC, diegonicita commented on src/ui/components/Toaster/Toaster.js
> +			if (!self.isConnected) {
Parece que webstorm solo pone un espacio antes y despues en los bloques de codigo principales y no en los bloques internos de ese bloque.  Busque una opcion pero no la encontre todavia.

2024-11-19 18:22 UTC, diegonicita commented on src/ui/components/Toaster/Toaster.js
> +				if (m_position.vertical === "center") {
Lo mismo de antes

2024-11-19 18:22 UTC, diegonicita commented on src/ui/components/Toaster/Toaster.js
> +					anchorOrigin: { horizontal: "left", vertical: "bottom" },
listo

2024-11-19 18:22 UTC, diegonicita commented on src/ui/themes/m-default.css
> +  --m-informative-color: #1C51A4;
listo

2024-11-19 18:22 UTC, alejandroscotti requested changes

2024-11-19 18:22 UTC, alejandroscotti commented on src/ui/components/Input/Input.css
> +  background-color: transparent;
Para que agregarle transparente? no seria mejor simplemente eliminar el color?

2024-11-19 18:22 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster-Orange.css
> +  background-color: transparent;
eliminar ` background-color: transparent;`??

2024-11-19 18:22 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster.css
> +  background-color: transparent;
eliminar

2024-11-19 18:22 UTC, alejandroscotti commented on src/ui/components/Toaster/Toaster.js
> +			};
Por que no hay renglon vacio despues del bloque de texto?

2024-11-19 18:52 UTC, diegonicita commented on src/ui/components/Toaster/Toaster-Orange.css
> +  background-color: transparent;
eliminado

2024-11-19 18:52 UTC, diegonicita commented on src/ui/components/Toaster/Toaster.css
> +  background-color: transparent;
eliminado

2024-11-19 18:52 UTC, diegonicita commented on src/ui/components/Input/Input.css
> +  background-color: transparent;
eliminado

2024-11-19 18:53 UTC, diegonicita commented on src/ui/components/Toaster/Toaster.js
> +			};
corregido

2024-11-20 02:42 UTC, alejandroscotti approved these changes

2024-11-20 02:42 UTC, merged